version: '3.4'
services:
  redis:
    restart: always
    image: 'redis'
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=hex.celery:app worker --loglevel='INFO'
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - 'media_volume:/media'
      - 'static_volume:/static'
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - '-c'
      - '/code/entrypoint_local.sh'
    ports:
      - '8000:8000'
    volumes:
      - '.:/code'
      - 'media_volume:/media'
      - 'static_volume:/code/static_shared'
    env_file:
      - .env
volumes:
  media_volume: null
  static_volume: null
