# Generated by Django 3.1.2 on 2020-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(max_length=255, upload_to='files')),
                ('finished', models.BooleanField(default=False, help_text='Only for task purposes', verbose_name='Processing finished')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='files', verbose_name='Thumbnail')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('pending', 'PENDING'), ('in_progress', 'IN PROGRESS'), ('finished', 'FINISHED'), ('postponed', 'POSTPONED'), ('canceled', 'CANCELED'), ('failed', 'FAILED')], default='new', max_length=50, verbose_name='Status')),
                ('threshold', models.PositiveIntegerField(default=15)),
                ('limit', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
